name: Build/release Moth's Cheats app

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        default: "1.0.0"
  # push:
  #   tags:
  #     - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: build
        # if: matrix.os == 'windows-latest'
        run: npm run build

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
